#!/bin/bash

cd /home/hammonja

touch _sensor1
touch _sensor2
touch db

i="0"

while [ $i -lt 4 ]
do

sensor1="NO"
sensor2="NO"

while [[ "$sensor1" == *NO* ]]
do
cat /sys/bus/w1/devices/28-0000040cb5aa/w1_slave > _sensor1;
sensor1=$(cat _sensor1);
cat _sensor1 >> /var/www/log1.html;
done

while [[ "$sensor2" == *NO* ]]
do
cat /sys/bus/w1/devices/28-0000040cb8b1/w1_slave > _sensor2;
sensor2=$(cat _sensor2);
cat _sensor2 >> /var/www/log2.html
done

VALOR=$(cat _sensor1 | grep t= | cut -f2 -d= | awk '{print $1/1000}')
VALOR2=$(cat _sensor2 | grep t= | cut -f2 -d= | awk '{print $1/1000}')

echo "<br>"$VALOR"<br>" >> /var/www/log1.html 
echo "<br>"$VALOR2"<br>" >> /var/www/log2.html 
T="$(echo $(($(date +%s%N)/1000000)))"
T2="$(date -u)"
echo ",["$T","$VALOR"]" >> middle
echo ",["$T","$VALOR2"]" >> middle2

cat startlive > /var/www/glive.html
cat middle >> /var/www/glive.html
cat mmiddle2 >> /var/www/glive.html
cat middle2 >> /var/www/glive.html
cat end >> /var/www/glive.html

echo "<P>Current Office Temp is :"$VALOR"<P> Current Outside Temp is :"$VALOR2"<P>last update @ "$T2"<p><img src='test.jpeg'</body></html>" >> /var/www/glive.html

fswebcam -d  /dev/video0 -r 640x480 /var/www/test.jpeg > /dev/null 2>&1

echo "INSERT INTO ``rances44``.``sensordata`` (``ID``, ``date``, ``sensor``, ``temp``) VALUES (NULL, NOW(),'28-0000040cb5aa', '"$VALOR"');" > db
echo "INSERT INTO ``rances44``.``sensordata`` (``ID``, ``date``, ``sensor``, ``temp``) VALUES (NULL, NOW(),'28-0000040cb8b1', '"$VALOR2"');" >> db

mysql -uroot -psophie1 rances44 < db


sleep 300

done
